name: Update Dependencies

on:
  # 手動觸發，可做用於任一 branch
  workflow_dispatch:
  # 排程觸發，只做用於 default branch
  schedule:
    - cron: "0 0 * * SUN" # In UTC time, 格式請參考: https://crontab.guru/

jobs:
  dep-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Update dependencies
        run: make update-dependencies
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          committer: bot <bot-noreply@softleader.com.tw>
          author: bot <bot-noreply@softleader.com.tw>
          body: >-
            chore: update dependencies
          labels: "dependencies-update"
          branch: "dep-update/${{ github.ref_name }}"
          delete-branch: true

  keepalive:
    runs-on: [self-hosted, ubuntu-jammy]
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
